/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssistantRouteImport } from './routes/admin.assistant'
import { Route as AdminCommunitiesRouteImport } from './routes/admin.communities'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminIdeasRouteImport } from './routes/admin.ideas'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminRecruitmentRouteImport } from './routes/admin.recruitment'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTalentRouteImport } from './routes/admin.talent'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCommunitiesRouteImport } from './routes/app.communities'
import { Route as AppIdeasRouteImport } from './routes/app.ideas'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppRecruitmentRouteImport } from './routes/app.recruitment'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as LoginStudentRouteImport } from './routes/login.student'
import { Route as AdminCommunitiesIndexRouteImport } from './routes/admin.communities.index'
import { Route as AdminCommunitiesIdRouteImport } from './routes/admin.communities.$id'
import { Route as AppCommunitiesIndexRouteImport } from './routes/app.communities.index'
import { Route as AppCommunitiesIdRouteImport } from './routes/app.communities.$id'
import { Route as AppIdeasIndexRouteImport } from './routes/app.ideas.index'
import { Route as AppIdeasIdRouteImport } from './routes/app.ideas.$id'
import { Route as AppPeopleIndexRouteImport } from './routes/app.people.index'
import { Route as AppPeopleIdRouteImport } from './routes/app.people.$id'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdeasRoute = AdminIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecruitmentRoute = AdminRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTalentRoute = AdminTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login/student',
  path: '/login/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunitiesIndexRoute = AdminCommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCommunitiesRoute,
} as any)
const AdminCommunitiesIdRoute = AdminCommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCommunitiesRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCommunitiesRoute,
} as any)
const AppCommunitiesIdRoute = AppCommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCommunitiesRoute,
} as any)
const AppIdeasIndexRoute = AppIdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdeasRoute,
} as any)
const AppIdeasIdRoute = AppIdeasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIdeasRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/communities': typeof AdminCommunitiesRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/talent': typeof AdminTalentRoute
  '/app/communities': typeof AppCommunitiesRouteWithChildren
  '/app/ideas': typeof AppIdeasRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/people': typeof AppPeopleRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/recruitment': typeof AppRecruitmentRoute
  '/app/settings': typeof AppSettingsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/student': typeof LoginStudentRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/communities/$id': typeof AdminCommunitiesIdRoute
  '/app/communities/$id': typeof AppCommunitiesIdRoute
  '/app/ideas/$id': typeof AppIdeasIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/app/communities/': typeof AppCommunitiesIndexRoute
  '/app/ideas/': typeof AppIdeasIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/talent': typeof AdminTalentRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruitment': typeof AppRecruitmentRoute
  '/app/settings': typeof AppSettingsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/student': typeof LoginStudentRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/communities/$id': typeof AdminCommunitiesIdRoute
  '/app/communities/$id': typeof AppCommunitiesIdRoute
  '/app/ideas/$id': typeof AppIdeasIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/admin/communities': typeof AdminCommunitiesIndexRoute
  '/app/communities': typeof AppCommunitiesIndexRoute
  '/app/ideas': typeof AppIdeasIndexRoute
  '/app/people': typeof AppPeopleIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/communities': typeof AdminCommunitiesRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/talent': typeof AdminTalentRoute
  '/app/communities': typeof AppCommunitiesRouteWithChildren
  '/app/ideas': typeof AppIdeasRouteWithChildren
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/people': typeof AppPeopleRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/recruitment': typeof AppRecruitmentRoute
  '/app/settings': typeof AppSettingsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/student': typeof LoginStudentRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/communities/$id': typeof AdminCommunitiesIdRoute
  '/app/communities/$id': typeof AppCommunitiesIdRoute
  '/app/ideas/$id': typeof AppIdeasIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/admin/communities/': typeof AdminCommunitiesIndexRoute
  '/app/communities/': typeof AppCommunitiesIndexRoute
  '/app/ideas/': typeof AppIdeasIndexRoute
  '/app/people/': typeof AppPeopleIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/assistant'
    | '/admin/communities'
    | '/admin/events'
    | '/admin/ideas'
    | '/admin/opportunities'
    | '/admin/projects'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/talent'
    | '/app/communities'
    | '/app/ideas'
    | '/app/messages'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/people'
    | '/app/profile'
    | '/app/projects'
    | '/app/recruitment'
    | '/app/settings'
    | '/login/admin'
    | '/login/student'
    | '/admin/'
    | '/app/'
    | '/admin/communities/$id'
    | '/app/communities/$id'
    | '/app/ideas/$id'
    | '/app/people/$id'
    | '/app/projects/$id'
    | '/admin/communities/'
    | '/app/communities/'
    | '/app/ideas/'
    | '/app/people/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/assistant'
    | '/admin/events'
    | '/admin/ideas'
    | '/admin/opportunities'
    | '/admin/projects'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/talent'
    | '/app/messages'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/profile'
    | '/app/recruitment'
    | '/app/settings'
    | '/login/admin'
    | '/login/student'
    | '/admin'
    | '/app'
    | '/admin/communities/$id'
    | '/app/communities/$id'
    | '/app/ideas/$id'
    | '/app/people/$id'
    | '/app/projects/$id'
    | '/admin/communities'
    | '/app/communities'
    | '/app/ideas'
    | '/app/people'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/assistant'
    | '/admin/communities'
    | '/admin/events'
    | '/admin/ideas'
    | '/admin/opportunities'
    | '/admin/projects'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/talent'
    | '/app/communities'
    | '/app/ideas'
    | '/app/messages'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/people'
    | '/app/profile'
    | '/app/projects'
    | '/app/recruitment'
    | '/app/settings'
    | '/login/admin'
    | '/login/student'
    | '/admin/'
    | '/app/'
    | '/admin/communities/$id'
    | '/app/communities/$id'
    | '/app/ideas/$id'
    | '/app/people/$id'
    | '/app/projects/$id'
    | '/admin/communities/'
    | '/app/communities/'
    | '/app/ideas/'
    | '/app/people/'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginAdminRoute: typeof LoginAdminRoute
  LoginStudentRoute: typeof LoginStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ideas': {
      id: '/admin/ideas'
      path: '/ideas'
      fullPath: '/admin/ideas'
      preLoaderRoute: typeof AdminIdeasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recruitment': {
      id: '/admin/recruitment'
      path: '/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/talent': {
      id: '/admin/talent'
      path: '/talent'
      fullPath: '/admin/talent'
      preLoaderRoute: typeof AdminTalentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communities': {
      id: '/app/communities'
      path: '/communities'
      fullPath: '/app/communities'
      preLoaderRoute: typeof AppCommunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ideas': {
      id: '/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruitment': {
      id: '/app/recruitment'
      path: '/recruitment'
      fullPath: '/app/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/student': {
      id: '/login/student'
      path: '/login/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/communities/': {
      id: '/admin/communities/'
      path: '/'
      fullPath: '/admin/communities/'
      preLoaderRoute: typeof AdminCommunitiesIndexRouteImport
      parentRoute: typeof AdminCommunitiesRoute
    }
    '/admin/communities/$id': {
      id: '/admin/communities/$id'
      path: '/$id'
      fullPath: '/admin/communities/$id'
      preLoaderRoute: typeof AdminCommunitiesIdRouteImport
      parentRoute: typeof AdminCommunitiesRoute
    }
    '/app/communities/': {
      id: '/app/communities/'
      path: '/'
      fullPath: '/app/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppCommunitiesRoute
    }
    '/app/communities/$id': {
      id: '/app/communities/$id'
      path: '/$id'
      fullPath: '/app/communities/$id'
      preLoaderRoute: typeof AppCommunitiesIdRouteImport
      parentRoute: typeof AppCommunitiesRoute
    }
    '/app/ideas/': {
      id: '/app/ideas/'
      path: '/'
      fullPath: '/app/ideas/'
      preLoaderRoute: typeof AppIdeasIndexRouteImport
      parentRoute: typeof AppIdeasRoute
    }
    '/app/ideas/$id': {
      id: '/app/ideas/$id'
      path: '/$id'
      fullPath: '/app/ideas/$id'
      preLoaderRoute: typeof AppIdeasIdRouteImport
      parentRoute: typeof AppIdeasRoute
    }
    '/app/people/': {
      id: '/app/people/'
      path: '/'
      fullPath: '/app/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/app/people/$id': {
      id: '/app/people/$id'
      path: '/$id'
      fullPath: '/app/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
  }
}

interface AdminCommunitiesRouteChildren {
  AdminCommunitiesIdRoute: typeof AdminCommunitiesIdRoute
  AdminCommunitiesIndexRoute: typeof AdminCommunitiesIndexRoute
}

const AdminCommunitiesRouteChildren: AdminCommunitiesRouteChildren = {
  AdminCommunitiesIdRoute: AdminCommunitiesIdRoute,
  AdminCommunitiesIndexRoute: AdminCommunitiesIndexRoute,
}

const AdminCommunitiesRouteWithChildren =
  AdminCommunitiesRoute._addFileChildren(AdminCommunitiesRouteChildren)

interface AdminRouteChildren {
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRoute
  AdminIdeasRoute: typeof AdminIdeasRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminRecruitmentRoute: typeof AdminRecruitmentRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTalentRoute: typeof AdminTalentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssistantRoute: AdminAssistantRoute,
  AdminCommunitiesRoute: AdminCommunitiesRouteWithChildren,
  AdminEventsRoute: AdminEventsRoute,
  AdminIdeasRoute: AdminIdeasRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminRecruitmentRoute: AdminRecruitmentRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTalentRoute: AdminTalentRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCommunitiesRouteChildren {
  AppCommunitiesIdRoute: typeof AppCommunitiesIdRoute
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
}

const AppCommunitiesRouteChildren: AppCommunitiesRouteChildren = {
  AppCommunitiesIdRoute: AppCommunitiesIdRoute,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
}

const AppCommunitiesRouteWithChildren = AppCommunitiesRoute._addFileChildren(
  AppCommunitiesRouteChildren,
)

interface AppIdeasRouteChildren {
  AppIdeasIdRoute: typeof AppIdeasIdRoute
  AppIdeasIndexRoute: typeof AppIdeasIndexRoute
}

const AppIdeasRouteChildren: AppIdeasRouteChildren = {
  AppIdeasIdRoute: AppIdeasIdRoute,
  AppIdeasIndexRoute: AppIdeasIndexRoute,
}

const AppIdeasRouteWithChildren = AppIdeasRoute._addFileChildren(
  AppIdeasRouteChildren,
)

interface AppPeopleRouteChildren {
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteChildren: AppPeopleRouteChildren = {
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteWithChildren = AppPeopleRoute._addFileChildren(
  AppPeopleRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppCommunitiesRoute: typeof AppCommunitiesRouteWithChildren
  AppIdeasRoute: typeof AppIdeasRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPeopleRoute: typeof AppPeopleRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppRecruitmentRoute: typeof AppRecruitmentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunitiesRoute: AppCommunitiesRouteWithChildren,
  AppIdeasRoute: AppIdeasRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPeopleRoute: AppPeopleRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppRecruitmentRoute: AppRecruitmentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginAdminRoute: LoginAdminRoute,
  LoginStudentRoute: LoginStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
